rescale_mid Rescale vector to have specified minimum, midpoint, and maximum.
#### Description
Rescale vector to have specified minimum, midpoint, and maximum.
#### Usage
rescale_mid(x, to, from, mid, ...)
## S3 method for class 'numeric'
rescale_mid(x, to = c(0, 1), from = range(x, na.rm =
TRUE), mid = 0, ...)
## S3 method for class 'logical'
rescale_mid(x, to = c(0, 1), from = range(x, na.rm =
TRUE), mid = 0, ...)
## S3 method for class 'dist'
rescale_mid(x, to = c(0, 1), from = range(x, na.rm =
TRUE), mid = 0, ...)
## S3 method for class 'POSIXt'
rescale_mid(x, to = c(0, 1), from = range(x, na.rm =
TRUE), mid, ...)
## S3 method for class 'Date'
rescale_mid(x, to = c(0, 1), from = range(x, na.rm =
TRUE), mid, ...)
## S3 method for class 'integer64'
rescale_mid(x, to = c(0, 1), from = range(x, na.rm
= TRUE), mid = 0, ...)
#### Arguments
x vector of values to manipulate.
to output range (numeric vector of length two)
from input range (vector of length two). If not given, is calculated from the range of
x
rescale_none 37
mid mid-point of input range
... other #### Arguments passed on to methods
#### Examples
rescale_mid(1:100, mid = 50.5)
rescale_mid(runif(50), mid = 0.5)
rescale_mid(1)
rescale_none Don’t perform rescaling
#### Description
Don’t perform rescaling
#### Usage
rescale_none(x, ...)
#### Arguments
x numeric vector of values to manipulate.
... all other #### Arguments ignored
#### Examples
rescale_none(1:100)
rescale_pal Rescale palette (continuous).
#### Description
Just rescales the input to the specific output range. Useful for alpha, size, and continuous position.
#### Usage
rescale_pal(range = c(0.1, 1))
#### Arguments
range Numeric vector of length two, giving range of possible values. Should be between
0 and 1.
38 scientific_format
reverse_trans Reverse transformation.
#### Description
Reverse transformation.
#### Usage
reverse_trans()
scientific_format Scientific formatter.
#### Description
Scientific formatter.
#### Usage
scientific_format(digits = 3, scale = 1, prefix = "", suffix = "",
decimal.mark = ".", trim = TRUE, ...)
scientific(x, digits = 3, scale = 1, prefix = "", suffix = "",
decimal.mark = ".", trim = TRUE, ...)
#### Arguments
digits Number of significant digits to show.
scale A scaling factor: x will be multiply by scale before formating (useful if the underlying
data is on another scale, e.g. for computing percentages or thousands).
prefix, suffix Symbols to display before and after value.
decimal.mark The character to be used to indicate the numeric decimal point.
trim Logical, if FALSE, values are right-justified to a common width (see base::format()).
... Other #### Arguments passed on to base::format().
x A numeric vector to format.
Value
A function with single parameter x, a numeric vector, that returns a character vector.
seq_gradient_pal 39
#### Examples
scientific_format()(1:10)
scientific_format()(runif(10))
scientific_format(digits = 2)(runif(10))
scientific(1:10)
scientific(runif(10))
scientific(runif(10), digits = 2)
scientific(12345, suffix = " cells/mL")
seq_gradient_pal Sequential colour gradient palette (continuous).
#### Description
Sequential colour gradient palette (continuous).
#### Usage
seq_gradient_pal(low = mnsl("10B 4/6"), high = mnsl("10R 4/6"),
space = "Lab")
#### Arguments
low colour for low end of gradient.
high colour for high end of gradient.
space colour space in which to calculate gradient. Must be "Lab" - other values are
deprecated.
#### Examples
x <- seq(0, 1, length.out = 25)
show_col(seq_gradient_pal()(x))
show_col(seq_gradient_pal("white", "black")(x))
library(munsell)
show_col(seq_gradient_pal("white", mnsl("10R 4/6"))(x))
40 sqrt_trans
