cscale Continuous scale.
#### Description
Continuous scale.
#### Usage
cscale(x, palette, na.value = NA_real_, trans = identity_trans())
#### Arguments
x vector of continuous values to scale
palette palette to use.
Built in palettes: area_pal, brewer_pal, dichromat_pal, div_gradient_pal,
gradient_n_pal, grey_pal, hue_pal, identity_pal, linetype_pal, manual_pal,
rescale_pal, seq_gradient_pal, shape_pal, viridis_pal
na.value value to use for missing values
trans transformation object describing the how to transform the raw data prior to scaling.
Defaults to the identity transformation which leaves the data unchanged.
Built in transformations: asn_trans, atanh_trans, boxcox_trans, date_trans,
exp_trans, hms_trans, identity_trans, log10_trans, log1p_trans, log2_trans,
log_trans, logit_trans, modulus_trans, probability_trans, probit_trans,
pseudo_log_trans, reciprocal_trans, reverse_trans, sqrt_trans, time_trans.
#### Examples
with(mtcars, plot(disp, mpg, cex = cscale(hp, rescale_pal())))
with(mtcars, plot(disp, mpg, cex = cscale(hp, rescale_pal(),
trans = sqrt_trans())))
with(mtcars, plot(disp, mpg, cex = cscale(hp, area_pal())))
with(mtcars, plot(disp, mpg, pch = 20, cex = 5,
col = cscale(hp, seq_gradient_pal("grey80", "black"))))
date_breaks 13
date_breaks Regularly spaced dates.
#### Description
Regularly spaced dates.
#### Usage
date_breaks(width = "1 month")
#### Arguments
width an interval specification, one of "sec", "min", "hour", "day", "week", "month",
"year". Can be by an integer and a space, or followed by "s". Fractional seconds
are supported.
date_format Formatted dates and times.
#### Description
Formatted dates and times.
#### Usage
date_format(format = "%Y-%m-%d", tz = "UTC")
time_format(format = "%H:%M:%S", tz = "UTC")
#### Arguments
format Date/time format using standard POSIX specification. See strptime() for possible
formats.
tz a time zone name, see timezones(). Defaults to UTC
#### Examples
a_time <- ISOdatetime(2012, 1, 1, 11, 30, 0, tz = "UTC")
a_date <- as.Date(a_time)
date_format()(a_date)
date_format(format = "%A")(a_date)
time_format()(a_time)
time_format(tz = "Europe/Berlin")(a_time)
14 dichromat_pal
a_hms <- hms::as.hms(a_time, tz = "UTC")
time_format(format = "%H:%M")(a_hms)
date_trans Transformation for dates (class Date).
#### Description
Transformation for dates (class Date).
#### Usage
date_trans()
#### Examples
years <- seq(as.Date("1910/1/1"), as.Date("1999/1/1"), "years")
t <- date_trans()
t$transform(years)
t$inverse(t$transform(years))
t$format(t$breaks(range(years)))
dichromat_pal Dichromat (colour-blind) palette (discrete).
#### Description
Dichromat (colour-blind) palette (discrete).
#### Usage
dichromat_pal(name)
#### Arguments
name Name of colour palette. One of: BrowntoBlue.10, BrowntoBlue.12, BluetoDarkOrange.12,
BluetoDarkOrange.18, DarkRedtoBlue.12, DarkRedtoBlue.18, BluetoGreen.14,
BluetoGray.8, BluetoOrangeRed.14, BluetoOrange.10, BluetoOrange.12,
BluetoOrange.8, LightBluetoDarkBlue.10, LightBluetoDarkBlue.7, Categorical.12,
GreentoMagenta.16, SteppedSequential.5
discard 15
#### Examples
show_col(dichromat_pal("BluetoOrange.10")(10))
show_col(dichromat_pal("BluetoOrange.10")(5))
# Can use with gradient_n to create a continous gradient
cols <- dichromat_pal("DarkRedtoBlue.12")(12)
show_col(gradient_n_pal(cols)(seq(0, 1, length.out = 30)))
discard Discard any values outside of range.
#### Description
Discard any values outside of range.
#### Usage
discard(x, range = c(0, 1))
#### Arguments
x numeric vector of values to manipulate.
range numeric vector of length two giving desired output range.
#### Examples
discard(c(-1, 0.5, 1, 2, NA))
div_gradient_pal Diverging colour gradient (continuous).
#### Description
Diverging colour gradient (continuous).
#### Usage
div_gradient_pal(low = mnsl("10B 4/6"), mid = mnsl("N 8/0"),
high = mnsl("10R 4/6"), space = "Lab")
#### Arguments
low colour for low end of gradient.
mid colour for mid point
high colour for high end of gradient.
space colour space in which to calculate gradient. Must be "Lab" - other values are
deprecated.
16 dollar_format
#### Examples
x <- seq(-1, 1, length.out = 100)
r <- sqrt(outer(x^2, x^2, "+"))
image(r, col = div_gradient_pal()(seq(0, 1, length.out = 12)))
image(r, col = div_gradient_pal()(seq(0, 1, length.out = 30)))
image(r, col = div_gradient_pal()(seq(0, 1, length.out = 100)))
library(munsell)
image(r, col = div_gradient_pal(low =
mnsl(complement("10R 4/6"), fix = TRUE))(seq(0, 1, length = 100)))
