

hue_pal Hue palette (discrete).
#### Description
Hue palette (discrete).
#### Usage
hue_pal(h = c(0, 360) + 15, c = 100, l = 65, h.start = 0,
direction = 1)
#### Arguments
h range of hues to use, in [0, 360]
c chroma (intensity of colour), maximum value varies depending on combination
of hue and luminance.
l luminance (lightness), in [0, 100]
h.start hue to start at
direction direction to travel around the colour wheel, 1 = clockwise, -1 = counter-clockwise
22 linetype_pal
#### Examples
show_col(hue_pal()(4))
show_col(hue_pal()(9))
show_col(hue_pal(l = 90)(9))
show_col(hue_pal(l = 30)(9))
show_col(hue_pal()(9))
show_col(hue_pal(direction = -1)(9))
show_col(hue_pal()(9))
show_col(hue_pal(h = c(0, 90))(9))
show_col(hue_pal(h = c(90, 180))(9))
show_col(hue_pal(h = c(180, 270))(9))
show_col(hue_pal(h = c(270, 360))(9))
identity_pal Identity palette.
#### Description
Leaves values unchanged - useful when the data is already scaled.
#### Usage
identity_pal()
identity_trans Identity transformation (do nothing).
#### Description
Identity transformation (do nothing).
#### Usage
identity_trans()
linetype_pal Line type palette (discrete).
#### Description
Based on a set supplied by Richard Pearson, University of Manchester
#### Usage
linetype_pal()
log1p_trans 23
log1p_trans Log plus one transformation.
#### Description
Log plus one transformation.
#### Usage
log1p_trans()
#### Examples
trans_range(log_trans(), 1:10)
trans_range(log1p_trans(), 0:9)
log_breaks Log breaks (integer breaks on log-transformed scales).
#### Description
Log breaks (integer breaks on log-transformed scales).
#### Usage
log_breaks(n = 5, base = 10)
#### Arguments
n desired number of breaks
base base of logarithm to use
#### Examples
log_breaks()(c(1, 1e6))
log_breaks()(c(1, 1e5))
log_breaks()(c(1664, 14008))
log_breaks()(c(407, 3430))
log_breaks()(c(1761, 8557))
24 math_format
log_trans Log transformation.
#### Description
Log transformation.
#### Usage
log_trans(base = exp(1))
#### Arguments
base base of logarithm
manual_pal Manual palette (manual).
#### Description
Manual palette (manual).
#### Usage
manual_pal(values)
#### Arguments
values vector of values to be used as a palette.
math_format Add arbitrary expression to a label. The symbol that will be replace
by the label value is .x.
#### Description
Add arbitrary expression to a label. The symbol that will be replace by the label value is .x.
#### Usage
math_format(expr = 10^.x, format = force)
muted 25
#### Arguments
expr expression to use
format another format function to apply prior to mathematical transformation - this
makes it easier to use floating point numbers in mathematical expressions.
Value
a function with single parameter x, a numeric vector, that returns a list of expressions
See Also
plotmath()
#### Examples
math_format()(1:10)
math_format(alpha + frac(1, .x))(1:10)
math_format()(runif(10))
math_format(format = percent)(runif(10))
muted Mute standard colour.
#### Description
Mute standard colour.
#### Usage
muted(colour, l = 30, c = 70)
#### Arguments
colour character vector of colours to modify
l new luminance
c new chroma
#### Examples
muted("red")
muted("blue")
show_col(c("red", "blue", muted("red"), muted("blue")))
26 number_bytes_format
number_bytes_format Bytes formatter: convert to byte measurement and display symbol.
#### Description
Bytes formatter: convert to byte measurement and display symbol.
#### Usage
number_bytes_format(symbol = "auto", units = "binary", ...)
number_bytes(x, symbol = "auto", units = c("binary", "si"), ...)
#### Arguments
symbol byte symbol to use. If "auto" the symbol used will be determined by the maximum
value of x. Valid symbols are "b", "Kb", "Mb", "Gb", "Tb", "Pb", "Eb",
"Zb", and "Yb", along with their upper case equivalents and "iB" equivalents.
units which unit base to use, "binary" (1024 base) or "si" (1000 base) for ISI units.
... Other arguments passed to number()
x a numeric vector to format
Value
a function with three parameters, x``, a numeric vector that returns a character vector,symbolthe byte symbol for ISI metric units).
#### References
Units of Information (Wikipedia) : http://en.wikipedia.org/wiki/Units_of_information
#### Examples
number_bytes_format()(sample(3000000000, 10))
number_bytes(sample(3000000000, 10))
number_bytes(sample(3000000000, 10), accuracy = .1)
number_format 27
number_format Number formatters
#### Description
A set of functions to format numeric values:
*  number_format() and number() are generic formatters for numbers.
*  comma_format() and comma() format numbers with commas separating thousands.
*  percent_format() and percent() multiply values by one hundred and display percent sign.
*  unit_format() add units to the values.
All formatters allow you to re-scale (multiplicatively), to round to specified accuracy, to add
custom suffix and prefix and to specify decimal.mark and big.mark.
#### Usage
number_format(accuracy = 1, scale = 1, prefix = "", suffix = "",
big.mark = " ", decimal.mark = ".", trim = TRUE, ...)
number(x, accuracy = 1, scale = 1, prefix = "", suffix = "",
big.mark = " ", decimal.mark = ".", trim = TRUE, ...)
comma_format(accuracy = 1, scale = 1, prefix = "", suffix = "",
big.mark = ",", decimal.mark = ".", trim = TRUE, digits, ...)
comma(x, accuracy = 1, scale = 1, prefix = "", suffix = "",
big.mark = ",", decimal.mark = ".", trim = TRUE, digits, ...)
percent_format(accuracy = NULL, scale = 100, prefix = "",
suffix = "%", big.mark = " ", decimal.mark = ".", trim = TRUE,
...)
percent(x, accuracy = NULL, scale = 100, prefix = "",
suffix = "%", big.mark = " ", decimal.mark = ".", trim = TRUE,
...)
unit_format(accuracy = 1, scale = 1, prefix = "", unit = "m",
sep = " ", suffix = paste0(sep, unit), big.mark = " ",
decimal.mark = ".", trim = TRUE, ...)
#### Arguments
accuracy Number to round to, NULL for automatic guess.
scale A scaling factor: x will be multiply by scale before formating (useful if the underlying
data is on another scale, e.g. for computing percentages or thousands).
28 number_format
prefix, suffix Symbols to display before and after value.
big.mark Character used between every 3 digits to separate thousands.
decimal.mark The character to be used to indicate the numeric decimal point.
trim Logical, if FALSE, values are right-justified to a common width (see base::format()).
... Other arguments passed on to base::format().
x A numeric vector to format.
digits Deprecated, use accuracy instead.
unit The units to append.
sep The separator between the number and the unit label.
Value
*_format() returns a function with single parameter x, a numeric vector, that returns a character
vector.
#### Examples
# number()
v <- c(12.3, 4, 12345.789, 0.0002)
number(v)
number(v, big.mark = ",")
number(v, accuracy = .001)
number(v, accuracy = .001, decimal.mark = ",")
number(v, accuracy = .5)
# number_format()
my_format <- number_format(big.mark = "'", decimal.mark = ",")
my_format(v)
# comma() and comma_format()
comma_format()(c(1, 1e3, 2000, 1e6))
comma_format(accuracy = .01)(c(1, 1e3, 2000, 1e6))
comma(c(1, 1e3, 2000, 1e6))
# percent() and percent_format()
percent_format()(runif(10))
percent(runif(10))
per_mille <- percent_format(
scale = 1000,
suffix = "\u2030",
accuracy = .1
)
per_mille(.1234)
french_percent <- percent_format(
decimal.mark = ",",
suffix = " %"
)
ordinal_format 29
french_percent(runif(10))
# unit_format()
# labels in kilometer when the raw data are in meter
km <- unit_format(unit = "km", scale = 1e-3, digits = 2)
km(runif(10) * 1e3)
# labels in hectares, raw data in square meters
ha <- unit_format(unit = "ha", scale = 1e-4)
km(runif(10) * 1e5)

