shape_pal Shape palette (discrete).
#### Description
Shape palette (discrete).
#### Usage
shape_pal(solid = TRUE)
#### Arguments
solid should shapes be solid or not?
show_col Show colours.
#### Description
A quick and dirty way to show colours in a plot.
#### Usage
show_col(colours, labels = TRUE, borders = NULL, cex_label = 1)
#### Arguments
colours a character vector of colours
labels boolean, whether to show the hexadecimal representation of the colours in each
tile
borders colour of the borders of the tiles; matches the border argument of graphics::rect().
The default means par("fg"). Use border = NA to omit borders.
cex_label size of printed labels, works the same as cex parameter of plot()
sqrt_trans Square-root transformation.
#### Description
Square-root transformation.
#### Usage
sqrt_trans()
squish 41
squish Squish values into range.
#### Description
Squish values into range.
#### Usage
squish(x, range = c(0, 1), only.finite = TRUE)
#### Arguments
x numeric vector of values to manipulate.
range numeric vector of length two giving desired output range.
only.finite if TRUE (the default), will only modify finite values.
Author(s)
Homer Strong homer.strong@gmail.com
#### Examples
squish(c(-1, 0.5, 1, 2, NA))
squish(c(-1, 0, 0.5, 1, 2))
squish_infinite Squish infinite values to range.
#### Description
Squish infinite values to range.
#### Usage
squish_infinite(x, range = c(0, 1))
#### Arguments
x numeric vector of values to manipulate.
range numeric vector of length two giving desired output range.
#### Examples
squish_infinite(c(-Inf, -1, 0, 1, 2, Inf))
42 train_continuous
time_trans Transformation for date-times (class POSIXt).
#### Description
Transformation for date-times (class POSIXt).
#### Usage
time_trans(tz = NULL)
#### Arguments
tz Optionally supply the time zone. If NULL, the default, the time zone will be
extracted from first input with a non-null tz.
#### Examples
hours <- seq(ISOdate(2000,3,20, tz = ""), by = "hour", length.out = 10)
t <- time_trans()
t$transform(hours)
t$inverse(t$transform(hours))
t$format(t$breaks(range(hours)))
train_continuous Train (update) a continuous scale
#### Description
Train (update) a continuous scale
#### Usage
train_continuous(new, existing = NULL)
#### Arguments
new New data to add to scale
existing Optional existing scale to update
train_discrete 43
train_discrete Train (update) a discrete scale
#### Description
Train (update) a discrete scale
#### Usage
train_discrete(new, existing = NULL, drop = FALSE, na.rm = FALSE)
#### Arguments
new New data to add to scale
existing Optional existing scale to update
drop TRUE, will drop factor levels not associated with data
na.rm If TRUE, will remove missing values
trans_breaks Pretty breaks on transformed scale.
#### Description
These often do not produce very attractive breaks.
#### Usage
trans_breaks(trans, inv, n = 5, ...)
#### Arguments
trans function of single variable, x, that given a numeric vector returns the transformed
values
inv inverse of the transformation function
n desired number of ticks
... other #### Arguments passed on to pretty
#### Examples
trans_breaks("log10", function(x) 10 ^ x)(c(1, 1e6))
trans_breaks("sqrt", function(x) x ^ 2)(c(1, 100))
trans_breaks(function(x) 1 / x, function(x) 1 / x)(c(1, 100))
trans_breaks(function(x) -x, function(x) -x)(c(1, 100))
44 trans_newro_range, 47
