
add_totals_col Append a totals column to a data.frame.
#### Description
This function is deprecated, use adorn_totals instead.
#### Usage <pre><code>
add_totals_col(dat, na.rm = TRUE)
</code></pre> #### Arguments
* ``dat``:  an input data.frame with at least one numeric column.
na.rm should missing values (including NaN) be omitted from the calculations?
Value
Returns a data.frame with a totals column containing row-wise sums.
add_totals_row 3
add_totals_row Append a totals row to a data.frame.
#### Description
This function is deprecated, use adorn_totals instead.
#### Usage <pre><code>
add_totals_row(dat, fill = "-", na.rm = TRUE)
</code></pre> #### Arguments
* ``dat``:  an input data.frame with at least one numeric column.
fill if there are more than one non-numeric columns, what string should fill the
bottom row of those columns?
na.rm should missing values (including NaN) be omitted from the calculations?
Value
Returns a data.frame with a totals row, consisting of "Total" in the first column and column sums in
the others.
adorn_crosstab Add presentation formatting to a crosstabulation table.
#### Description
This function is deprecated, use the adorn_ family of functions instead.
#### Usage <pre><code>
adorn_crosstab(dat, denom = "row", show_n = TRUE, digits = 1,
show_totals = FALSE, rounding = "half to even")
</code></pre> #### Arguments
* ``dat``: a data.frame with row names in the first column and numeric values in all other
columns. Usually the piped-in result of a call to crosstab that included the
argument percent = "none".
* ``denom``:  the denominator to use for calculating percentages. One of "row", "col", or "all".
show_n should counts be displayed alongside the percentages?
* ``digits``: how many digits should be displayed after the decimal point?
show_totals display a totals summary? Will be a row, column, or both depending on the
value of denom.
rounding method to use for truncating percentages - either "half to even", the base R
default method, or "half up", where 14.5 rounds up to 15.
4 adorn_ns
Value
Returns a data.frame.
adorn_ns Add underlying Ns to a tabyl displaying percentages.
#### Description
This function adds back the underlying Ns to a tabyl whose percentages were calculated using
adorn_percentages(), to display the Ns and percentages together. You can also call it on a nontabyl
data.frame with tabyl-like format to which you wish to append Ns.
#### Usage <pre><code>
adorn_ns(dat, position = "rear", ns = attr(dat, "core"))
</code></pre> #### Arguments
* ``dat``: a data.frame of class tabyl that has had adorn_percentages and/or adorn_pct_formatting
called on it. If given a list of data.frames, this function will apply itself to each
data.frame in the list (designed for 3-way tabyl lists).
position should the N go in the front, or in the rear, of the percentage?
ns the Ns to append. The default is the "core" attribute of the input tabyl dat, where
the original Ns of a two-way tabyl are stored. However, if you need to modify
the numbers, e.g., to format 4000 as 4,000 or 4k, you can do that separately and
supply the formatted result here.
Value
a data.frame with Ns appended
#### Examples
mtcars %>%
tabyl(am, cyl) %>%
adorn_percentages("col") %>%
adorn_pct_formatting() %>%
adorn_ns(position = "front")




