untabyl Remove tabyl attributes from a data.frame.
#### Description
Strips away all tabyl-related attributes from a data.frame.
#### Usage <pre><code>
untabyl(dat)
</code></pre> #### Arguments
* ``dat``: a data.frame of class tabyl.
Value
Returns the same data.frame, but without the tabyl class and attributes.
#### Examples
mtcars %>%
tabyl(am) %>%
untabyl() %>%
attributes() # tabyl-specific attributes are gone
use_first_valid_of Returns first non-NA value from a set of vectors.
#### Description
At each position of the input vectors, iterates through in order and returns the first non-NA value.
This is a robust replacement of the common ifelse(!is.na(x), x, ifelse(!is.na(y), y, z)).
It’s more readable and handles problems like ifelse’s inability to work with dates in this way.
#### Usage <pre><code>
use_first_valid_of(..., if_all_NA = NA)
</code></pre> #### Arguments
... the input vectors. Order matters: these are searched and prioritized in the order
they are supplied.
if_all_NA what value should be used when all of the vectors return NA for a certain index?
Default is NA.
use_first_valid_of 21
Value
Returns a single vector with the selected values.
Warning
Deprecated, do not use in new code. Use dplyr::coalesce() instead.
See Also
janitor_deprecated
Index
add_totals_col, 2
add_totals_row, 3
adorn_crosstab, 3
adorn_ns, 4
adorn_pct_formatting, 5
adorn_percentages, 5
adorn_rounding, 6
adorn_title, 7
adorn_totals, 8
as_tabyl, 9
clean_names, 10
convert_to_NA, 11, 14
crosstab, 12
excel_numeric_to_date, 13
get_dupes, 14
janitor_deprecated, 14
remove_empty, 15
remove_empty_cols, 15
remove_empty_rows, 16
round_half_up, 16
row_to_names, 17
tabyl, 18
to_any_case, 11
top_levels, 19
untabyl, 20
use_first_valid_of, 14, 20
22
