`geom_density2d` and `stat_density2d`
========================================================

### Preliminaries

```{r}
library(ggplot2)
library(MASS)
data(geyser)
head(geyser)
```


```{r fig.width=7, fig.height=6}

m <- ggplot(geyser, aes(x = duration, y = waiting)) +
  geom_point() + xlim(0.5, 6) + ylim(40, 110)
m
# Add contours
m + geom_density2d()
```


```{r fig.width=7, fig.height=6}
dens <- kde2d(geyser$duration, geyser$waiting, n = 50,
              lims = c(0.5, 6, 40, 110))
densdf <- data.frame(expand.grid(duration = dens$x, waiting = dens$y),
 z = as.vector(dens$z))
head(densdf)
m + geom_contour(aes(z=z), data=densdf)
```


```{r fig.width=7, fig.height=6}
m + geom_density2d() + scale_y_log10()
m + geom_density2d() + coord_trans(y="log10")

m + stat_density2d(aes(fill = ..level..), geom="polygon")
```


```{r fig.width=7, fig.height=6}
qplot(duration, waiting, data=geyser, geom=c("point","density2d")) +
  xlim(0.5, 6) + ylim(40, 110)
```

### Diamonds Data Set

If you map an aesthetic to a categorical variable, you will get a
set of contours for each value of that variable

```{r fig.width=7, fig.height=6}
set.seed(4393)
dsmall <- diamonds[sample(nrow(diamonds), 1000), ]
qplot(x, y, data = dsmall, geom = "density2d", colour = cut)
qplot(x, y, data = dsmall, geom = "density2d", linetype = cut)
qplot(carat, price, data = dsmall, geom = "density2d", colour = cut)
d <- ggplot(dsmall, aes(carat, price)) + xlim(1,3)
d + geom_point() + geom_density2d()
```
If we turn contouring off, we can use use geoms like tiles:

```{r fig.width=7, fig.height=6}
d + stat_density2d(geom="tile", aes(fill = ..density..), contour = FALSE)
last_plot() + scale_fill_gradient(limits=c(1e-5,8e-4))
```
```{r fig.width=7, fig.height=6}
# Or points:
d + stat_density2d(geom="point", aes(size = ..density..), contour = FALSE)

```

