`geom_boxplot`
========================================================


```{r fig.width=7, fig.height=6}
library(ggplot2)
p <- ggplot(mtcars, aes(factor(cyl), mpg))

p + geom_boxplot()

```
### Using Quickplot
```{r fig.width=7, fig.height=6}
qplot(factor(cyl), mpg, data = mtcars, geom = "boxplot")
```
### `jitter` and `coord_flip`
```{r fig.width=7, fig.height=6}
p + geom_boxplot() + geom_jitter()
p + geom_boxplot() + coord_flip()
# Quickplot Variant
qplot(factor(cyl), mpg, data = mtcars, geom = "boxplot") +
  coord_flip()
```
### Notched Boxplots
```{r fig.width=7, fig.height=6}
p + geom_boxplot(notch = TRUE)
p + geom_boxplot(notch = TRUE, notchwidth = .3)

p + geom_boxplot(outlier.colour = "darkred", outlier.size = 4)

```
### Adding aesthetic mappings
Note that boxplots are automatically dodged when any aesthetic is
a factor.
```{r fig.width=7, fig.height=6}

p + geom_boxplot(aes(fill = cyl))
p + geom_boxplot(aes(fill = factor(cyl)))
p + geom_boxplot(aes(fill = factor(vs)))
p + geom_boxplot(aes(fill = factor(am)))
```

### Set aesthetics to fixed value
```{r fig.width=7, fig.height=6}
p + geom_boxplot(fill = "grey80", colour = "#3366FF")
qplot(factor(cyl), mpg, data = mtcars, geom = "boxplot",
  colour = I("#3366FF"))

# Scales vs. coordinate transforms -------
# Scale transformations occur before the boxplot statistics are computed.
# Coordinate transformations occur afterwards.  Observe the effect on the
# number of outliers.
library(plyr) # to access round_any
m <- ggplot(movies, aes(y = votes, x = rating,
   group = round_any(rating, 0.5)))
m + geom_boxplot()
m + geom_boxplot() + scale_y_log10()
m + geom_boxplot() + coord_trans(y = "log10")
m + geom_boxplot() + scale_y_log10() + coord_trans(y = "log10")

# Boxplots with continuous x:
# Use the group aesthetic to group observations in boxplots
qplot(year, budget, data = movies, geom = "boxplot")
qplot(year, budget, data = movies, geom = "boxplot",
  group = round_any(year, 10, floor))

# Using precomputed statistics
# generate sample data
abc <- adply(matrix(rnorm(100), ncol = 5), 2, quantile, c(0, .25, .5, .75, 1))
b <- ggplot(abc, aes(x = X1, ymin = `0%`, lower = `25%`, middle = `50%`, upper = `75%`, ymax = `100%`))
b + geom_boxplot(stat = "identity")
b + geom_boxplot(stat = "identity") + coord_flip()
b + geom_boxplot(aes(fill = X1), stat = "identity")

```

