`geom_abline`
========================================================

```{r fig.width=7, fig.height=6}
library(ggplot2)
p <- qplot(wt, mpg, data = mtcars)
```
### Fixed slopes and intercepts
```{r fig.width=7, fig.height=6}

p + geom_abline() # Can't see it - outside the range of the data
p + geom_abline(intercept = 20)
```
### Calculate slope and intercept of line of best fit

```{r fig.width=7, fig.height=6}
coef(lm(mpg ~ wt, data = mtcars))
p + geom_abline(intercept = 37, slope = -5)
p + geom_abline(intercept = 10, colour = "red", size = 2)
```


```{r fig.width=7, fig.height=6}
# See ?stat_smooth for fitting smooth models to data
p + stat_smooth(method="lm", se=FALSE)
```
### Slopes and intercepts as data

```{r fig.width=7, fig.height=6}

p <- ggplot(mtcars, aes(x = wt, y=mpg), . ~ cyl) + geom_point()
df <- data.frame(a=rnorm(10, 25), b=rnorm(10, 0))
p + geom_abline(aes(intercept=a, slope=b), data=df)
```

### Slopes and intercepts from linear model
```{r fig.width=7, fig.height=6}
library(plyr)
coefs <- ddply(mtcars, .(cyl), function(df) {
  m <- lm(mpg ~ wt, data=df)
  data.frame(a = coef(m)[1], b = coef(m)[2])
})
str(coefs)
p + geom_abline(data=coefs, aes(intercept=a, slope=b))
```


```{r fig.width=7, fig.height=6}
# It's actually a bit easier to do this with stat_smooth
p + geom_smooth(aes(group=cyl), method="lm")
p + geom_smooth(aes(group=cyl), method="lm", fullrange=TRUE)
```

### With coordinate transforms
```{r fig.width=7, fig.height=6}

p + geom_abline(intercept = 37, slope = -5) + coord_flip()
p + geom_abline(intercept = 37, slope = -5) + coord_polar()

```

