ggplot2 Regression
========================================================

Basic scatterplots with regression lines

#### preliminary

```{r}
library(ggplot2)
set.seed(955)
# Make some noisily increasing data
dat <- data.frame(cond = rep(c("A", "B"), each=10),
                  xvar = 1:20 + rnorm(20,sd=3),
                  yvar = 1:20 + rnorm(20,sd=3))
head(dat)
```
#### Part 1 Basic Plot
```{r fig.width=7, fig.height=6}

ggplot(dat, aes(x=xvar, y=yvar)) +
    geom_point(shape=1)      # Use hollow circles

```
#### Part 2 Add Regression Line
```{r fig.width=7, fig.height=6}
ggplot(dat, aes(x=xvar, y=yvar)) +
    geom_point(shape=1) +    # Use hollow circles
    geom_smooth(method=lm,alpha=0.90)   # Add linear regression line 
                             
```
#### Part 3 Regression Line
```{r fig.width=7, fig.height=6}
ggplot(dat, aes(x=xvar, y=yvar)) +
    geom_point(shape=1) +    # Use hollow circles
    geom_smooth(method=lm,   # Add linear regression line
                se=FALSE)    # Don't add shaded confidence region
```
#### Part 4 
Add a loess smoothed fit curve with confidence region
```{r fig.width=7, fig.height=6}
ggplot(dat, aes(x=xvar, y=yvar)) +
    geom_point(shape=1) +    # Use hollow circles
    geom_smooth()            # 
```


